spring.application.name=sop-audit-service
server.port=8081


#RabbitMQ Properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest


spring.rabbitmq.listener.simple.acknowledge-mode=manual
# Отключим встроенные ретраи, чтобы сразу видеть работу DLQ
spring.rabbitmq.listener.simple.retry.enabled=false 


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.metrics.export.prometheus.enabled=true
spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true


# Audit CSV Storage
audit.csv.base-dir=./audit-data/csv
audit.csv.retention-days=30
audit.csv.max-file-size-mb=100
audit.csv.days-to-load=7

# Audit Report Storage
audit.reports.base-dir=./audit-data/reports
audit.reports.retention-days=90


# Scheduled Tasks Configuration
audit.schedule.file-cleanup=0 0 3 * * ?
audit.schedule.report-cleanup=0 0 4 * * ?
audit.schedule.daily-report=0 59 23 * * ?
audit.schedule.recalculation-interval-ms=600000


