spring.application.name=sop-grpcclient-calc
server.port=8082


#RabbitMQ Properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest



# Включаем publisher confirms. correlated - для отслеживания, simple - просто true/false
spring.rabbitmq.publisher-confirm-type=correlated
# Включаем publisher returns, чтобы знать, если сообщение не дошло до очереди
spring.rabbitmq.publisher-returns=true
# Шаблон для RabbitTemplate, чтобы все сообщения по умолчанию были персистентными
spring.rabbitmq.template.mandatory=true


spring.rabbitmq.listener.simple.acknowledge-mode=manual
# Отключим встроенные ретраи, чтобы сразу видеть работу DLQ
spring.rabbitmq.listener.simple.retry.enabled=false 


grpc.client.credit-calc-service.address=static://localhost:9090
grpc.client.credit-calc-service.negotiation-type=plaintext


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.metrics.export.prometheus.enabled=true
spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true
